# Generated by Django 4.0.1 on 2022-02-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0002_signupform_delete_profileform'),
    ]

    operations = [
        migrations.CreateModel(
            name='agreementsellform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_address', models.CharField(max_length=30)),
                ('agree_date', models.CharField(max_length=30)),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_age', models.CharField(max_length=30)),
                ('seller_occ', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('buyer_name', models.CharField(max_length=30)),
                ('buyer_age', models.CharField(max_length=30)),
                ('buyer_occ', models.CharField(max_length=30)),
                ('buyer_address', models.CharField(max_length=30)),
                ('property_address', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('token_amount', models.CharField(max_length=30)),
                ('bal_amount', models.CharField(max_length=30)),
                ('bal_date', models.CharField(max_length=30)),
                ('extra_variable', models.CharField(max_length=30)),
            ],
        ),
    ]
