# Generated by Django 4.0.1 on 2022-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0004_alter_agreementsellform_agree_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementsellform',
            name='extra_variable',
            field=models.DateField(max_length=30),
        ),
    ]
