# Generated by Django 4.0.1 on 2022-02-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0005_alter_agreementsellform_extra_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementsellform',
            name='agree_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='bal_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='bal_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='buyer_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='extra_variable',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='seller_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agreementsellform',
            name='token_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
